### ISSUE TITLE
Illegal offset type in isset or empty in /vendor/yiisoft/yii2/helpers/BaseArrayHelper.php:528

### ISSUE THREAD

**Issue by Jasurbek94** [mehdikhody/bot#1]
hi everyone it doesnot matter what i do with bot it always returns the same result 
```php
$bot = new \bot\Bot([
    'token' => $token
]);

$chat_id = Bot::$chat->getId();
$file = new InputFile('@webroot/favicon.ico');

$response = Bot::$api->sendPhoto()
    ->setChatId($chat_id)
    ->setPhoto($file)
    ->send();
```

**Comment by mehdikhody** [comment]
hi, `Bot::$chat` only worked when telegram send json updates to your php file.
you can't use it and `$chat->getId()` is error because Chat object not exists.

for fix this problem, set your bot webhook address or use getUpdates method to run your bot in command line, [read here](https://github.com/mehdikhody/bot/wiki/Example:-Get-updates).

**Comment by Jasurbek94** [comment]
i have allready set webhook before using the plugin! should i do it every time?

**Comment by mehdikhody** [comment]
If you set webhook before, there is no need to set webhook again.
For example, webhook address like follow line:
```
https://example.com/index.php?r=site/webhook
```

Now you should create Bot object in `@app/controllers/SiteController.php`.
follow lines:
```
public function actionWebhook()
{
    $bot = new \bot\Bot([
        'token' => $token
    ]);
    
    // your actions, like send hello message
    $chat_id = Bot::$chat->getId();
    $response = Bot::$api->sendMessage()
        ->setChatId($chat_id)
        ->setText('Hello')
        ->send();
}
```

To test the bot go to telegram messenger and send `/start`.

> Webhook Note:
> Ports currently supported for Webhooks: 443, 80, 88, 8443.
>
> If you're having any trouble setting up webhooks, please check out this [amazing guide to Webhooks](https://core.telegram.org/bots/webhooks).

**Comment by Jasurbek94** [comment]
2017-09-08 13:29:45
 [-][-][error][yii\base\ErrorException:2] yii\base\ErrorException: Illegal offset type in isset or empty in /var/www/html/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php:528
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php(528): yii\base\ErrorHandler->handleError(2, 'Illegal offset ...', '/var/www/html/v...', 528, Array)
#1 /var/www/html/vendor/khoram/bot/base/Object.php(77): yii\helpers\BaseArrayHelper::keyExists(Object(bot\helper\Property), Array)
#2 /var/www/html/vendor/khoram/bot/base/Object.php(196): bot\base\Object->__isset(Object(bot\helper\Property))
#3 /var/www/html/vendor/khoram/bot/object/Update.php(65): bot\base\Object->__call('message', Array)
#4 /var/www/html/vendor/khoram/bot/base/Bot.php(434): bot\object\Update->getFrom()
#5 /var/www/html/vendor/khoram/bot/base/Bot.php(374): bot\base\Bot->setUpdate(Array)
#6 /var/www/html/vendor/yiisoft/yii2/base/Object.php(107): bot\base\Bot->init()
#7 /var/www/html/frontend/controllers/MyTelegramController.php(137): yii\base\Object->__construct(Array)
#8 [internal function]: frontend\controllers\MyTelegramController->actionRequest('39')
#9 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('request', Array)
#12 /var/www/html/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('my-telegram/req...', Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Application.php(382): yii\web\Application->handleRequest(Object(yii\web\Request))
#14 /var/www/html/frontend/web/index.php(40): yii\base\Application->run()
#15 {main}

$_SERVER = [
    'USER' => 'nobody'
    'HOME' => '/nonexistent'
    'HTTP_CONTENT_TYPE' => 'application/json'
    'HTTP_CF_VISITOR' => '{\"scheme\":\"https\"}'
    'HTTP_X_FORWARDED_PROTO' => 'https'
    'HTTP_CONTENT_LENGTH' => '345'
    'HTTP_CF_RAY' => '39b24227dcdc6b61-LHR'
    'HTTP_X_FORWARDED_FOR' => '149.154.167.203'
    'HTTP_CF_IPCOUNTRY' => 'GB'
    'HTTP_ACCEPT_ENCODING' => 'gzip'
    'HTTP_CONNECTION' => 'Keep-Alive'
    'REDIRECT_STATUS' => '200'
    'SERVER_NAME' => '_'
    'SERVER_PORT' => '443'
    'REMOTE_PORT' => '12694'
    'REMOTE_ADDR' => '141.101.99.150'
    'SERVER_SOFTWARE' => 'nginx/1.13.3'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'REQUEST_SCHEME' => 'https'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'DOCUMENT_ROOT' => '/var/www/html'
    'DOCUMENT_URI' => '/frontend/web/index.php'
    'REQUEST_URI' => '/request/39'
    'SCRIPT_NAME' => '/frontend/web/index.php'
    'CONTENT_LENGTH' => '345'
    'CONTENT_TYPE' => 'application/json'
    'REQUEST_METHOD' => 'POST'
    'QUERY_STRING' => ''
    'HTTPS' => 'on'
    'SCRIPT_FILENAME' => '/var/www/html/frontend/web/index.php'
    'FCGI_ROLE' => 'RESPONDER'
    'PHP_SELF' => '/frontend/web/index.php'
    'REQUEST_TIME_FLOAT' => 1504877384.9963
    'REQUEST_TIME' => 1504877384
]

**Comment by Jasurbek94** [comment]
this is error after executing the script which you have given me

**Comment by mehdikhody** [comment]
I told you, this page should be executed by telegram server, not your browser.
go to your [telegram](https://web.telegram.org/) account and send new message in your bot.

**[Telegram web](https://web.telegram.org/)**
https://web.telegram.org/
